### ISSUE TITLE
Helm Chart - Check prometheus CRD availability before creating ServiceMonitor - PodMonitor - PrometheusRule  resources

### ISSUE THREAD

**Issue by cmontemuino** [openebs/monitoring#107]
Given that the prometheus-stack dependency can be disabled (see `condition: kube-prometheus-stack.install`), adding a couple of guardrails to prometheus resources might make sense:

- `templates/podmonitors.yaml`
- `templates/prometheusRules.yaml`
- `templates/servicemonitors.yaml`

**Comment by cmontemuino** [comment]
I can open a PR if that helps.

**Comment by datacore-vvarakantham** [comment]
Sure, please proceed to open a PR.

**Comment by cmontemuino** [comment]
Hi @datacore-vvarakantham, I've just opened an PR to address this issue: https://github.com/openebs/monitoring/pull/108
