### ISSUE TITLE
Deprecation Warning in k8s 1.21

### ISSUE THREAD

**Issue by dyasny** [openebs/monitoring#40]
On a fresh 1.21.2 deployment I am getting the following:

```
W0714 11:03:34.634539 1922149 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
```

Versions:
helm version.BuildInfo{Version:"v3.6.0", GitCommit:"7f2df6467771a75f5646b7f12afb408590ed1755", GitTreeState:"clean", GoVersion:"go1.16.3"}
kubernetes: v1.21.2

**Comment by datacore-vvarakantham** [comment]
@dyasny The [PR](https://github.com/openebs/monitoring/pull/103)  includes the changes to disable the PSP and resolves the issue, has been merged.

**Comment by avishnu** [comment]
Closing based on the above comment.
