### ISSUE TITLE
Support for Mayastor dashboards

### ISSUE THREAD

**Issue by kmova** [openebs/monitoring#46]
Similar to cStor Overview dashboard, provide overview dashboards for other engines like:
- Jiva
- Local PV Flavors
- Mayastor

**Comment by avishnu** [comment]
Added dashboards for Mayastor with this PR #110

**Comment by w3aman** [comment]
LVM and ZFS LocalPV dashboards are available, mainly focused on VolGroup and ZPOOL's respectively.
