### ISSUE TITLE
cStor Volume Replica Dashboard is displaying information about cStor volumes and not it's replicas.

### ISSUE THREAD

**Issue by Ab-hishek** [openebs/monitoring#50]
cStor volume replica dashboard has a `replicas` variable which gets its value from the following query:
 `"label_values(openebs_replica_status{cstor_pool="$Pool"}, vol)"`. But this query only returns the volume name of the replicas and not exactly the individual replicas. However, the metric: `openebs_replica_status` contains separate rows for each replica but has the `vol` label same for the replicas that belong to the same volume. 

Currently, there is no cStor metric available that could help us identify the individual replicas. Therefore the dashboard seems inconsistent with its naming and definition. All the panels inside this dashboard for eg: `replica status`, `replica rebuild count` and others defeats the purpose of visualising each replicas as a separate indentity.

**Comment by avishnu** [comment]
This issue is no longer applicable as CStor has now been deprecated.
