### ISSUE TITLE
Stateful Workload Dashboard: Set the tag as "OpenEBS" instead of "openEBS"

### ISSUE THREAD

**Issue by kmova** [openebs/monitoring#75]
Ref Dashboard: https://github.com/openebs/monitoring/blob/develop/jsonnet/openebs-mixin/dashboards/openebs/localpv-workload.json#L3954

Only this dashboard spells the tag as `openEBS` instead of `OpenEBS`.

**Comment by omeiirr** [comment]
@kmova I'd like to resolve this

**Comment by kmova** [comment]
thanks @omeiirr. go for it!

**Comment by omeiirr** [comment]
@kmova Please review [here](https://github.com/openebs/monitoring/pull/76)
