### ISSUE TITLE
Stateful Workload Dashboard: include `zfs` to the regular expression

### ISSUE THREAD

**Issue by kmova** [openebs/monitoring#77]
The Stateful workload dashboard capture the filesystem statistics for only `ext4` or `xfs`. This is done via a regular expression like `ext4|xfs`. 

Example: https://github.com/openebs/monitoring/blob/develop/jsonnet/openebs-mixin/dashboards/openebs/localpv-workload.json#L1929

In all of the above occurrences, include `zfs` as a filesystem option. The valid expression should be `ext4|xfs|zfs`.

**Comment by rweilg** [comment]
Hello, can I take care of this?

**Comment by kmova** [comment]
Thank @rweilg for fixing this!!
