### ISSUE TITLE
add a dashboard to show PV capacity

### ISSUE THREAD

**Issue by survivant** [openebs/monitoring#85]
to help the support team with the monitoring it should be important to include a visual aid that show the disk capacity. 

I found a nice Grafana dashboard here : https://github.com/sstarcher/grafana-dashboards/blob/master/prometheus/pv.json

it show all the PVC  with the used space and free space.

![image](https://user-images.githubusercontent.com/191879/137136415-b4552ef1-1007-41e1-adfd-15f58598cd83.png)

**Comment by survivant** [comment]
that PR should allow the user to extend the OpenEBS monitoring stack : https://github.com/openebs/monitoring/pull/95 

but it still could be useful to have a official dashboard from OpenEBS team that will show the PV capacity

**Comment by avishnu** [comment]
The dashboards from the node exporter stack should suffice.
