### ISSUE TITLE
add dashboard for Node Exporter

### ISSUE THREAD

**Issue by survivant** [openebs/monitoring#86]
OpenEBS monitoring stack monitor Node exporter metrics, but it could be useful to have a dashboard that show those metrics.

I found a nice Grafana dashboard here : https://github.com/rfrail3/grafana-dashboards

![image](https://user-images.githubusercontent.com/191879/137140367-43d87c03-28dd-4c1a-a52f-aff25f869d7d.png)

**Comment by survivant** [comment]
that PR should allow the user to extend the OpenEBS monitoring stack : https://github.com/openebs/monitoring/pull/95

**Comment by avishnu** [comment]
The framework allows for user/custom dashboards to be imported. Closing this issue.
